### ISSUE TITLE
Support intelligent diagnosis Feature Task List

### ISSUE THREAD

**Issue by tangcong** [tkestack/kstone#124]
- [ ]  diagnosing proposal 
- [ ]  diagnosing framework (strong scalability)
- [ ]  various detection plugins
- [ ]  dashboard supports intelligent diagnosis feature
- [ ]  e2e tests
