### ISSUE TITLE
todo list discussion

### ISSUE THREAD

**Issue by lianghao208** [tkestack/kstone#2]
This issue is raised for kstone todo list discussion:

* [ ]  unit/e2e test in GitHub
* [ ]  create CI job in GitHub
* [ ]  add learner node support in kstone-dashboard

**Comment by tangcong** [comment]
thanks. we will do the above things next. At the same time, I add some other tasks.

- [ ] Make kstone-etcd-operator open source as soon as possible （P0)
- [ ] support [more object storages]( https://github.com/tkestack/kstone/tree/master/pkg/backup/providers), such as s3, oss. hope everyone can contribute. (P3)
- [ ] kstone-dashboard supports adding/updating key-values.(P3)
- [ ] kstone-dashboard supports multiple languages. (P2)
