### ISSUE TITLE
kstone authentication support task list

### ISSUE THREAD

**Issue by lianghao208** [tkestack/kstone#98]
* [x] submit proposal doc[#88 ]
* [x] kstone-api supports token provider, token generator and authenticator interface[#99 ]
* [ ] kstone-api supports auth webhook
* [x] kstone-dashboard supports login feature[#103 ]
* [x] kstone-dashboard supports change password feature[#103 ]
* [x] kstone-api supports login/middleware router[#103 ]

**Comment by tangcong** [comment]
https://github.com/tkestack/kstone/releases/tag/v0.2.0-beta.1 has supported authentication.
thanks @lianghao208 @engow
